
services:
  db:
    image: postgres
    restart: always
    container_name: database-api
    environment:
      POSTGRES_USER: DEV
      POSTGRES_PASSWORD: PASS
      POSTGRES_DB: MAIN
    ports:
      - "2100:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
  api:
    container_name: api-service
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    environment:
      PORT: 1092
    ports:
      - "1092:1092"
    depends_on:
      - db

volumes:
  db-volume: