

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: mysql_pwd
    ports:
      - "2100:3306"
    volumes:
      - db-volume:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PORT: 1092
    ports:
      - "1092:1092"
    depends_on:
      - db

volumes:
  db-volume: